import config from '../../../config';
import { IUser } from './user.interface';
import { User } from './user.model';
import { genereteUserId } from './user.utils';

const createUser = async (user: IUser): Promise<IUser | null> => {
  // autogenerated incremental user id
  const id = await genereteUserId();
  user.id = id;

  // default password
  if (!user.password) {
    user.password = config.default_user_pass as string;
  }

  const createdUser = await User.create(user);

  if (!createdUser) {
    throw new Error('Failed to create user');
  }
  return createdUser;
};

export default {
  createUser,
};
